### ISSUE TITLE
Add surface mobs

### ISSUE THREAD

**Issue by Jack-Papel** [devs-immortal/Paradise-Lost#232]
(As is displayed in https://github.com/devs-immortal/The-Aether/projects/4)
Add:
- [ ] ~~Phyg,~~ (Will be replaced)
- [ ] ~~Flying Cow,~~ (Will be replaced)
- [ ] ~~Sheepuff,~~ (Will be replaced)
- [x] ~~Swet,~~ (Added, for the most part)
- [x] ~~Moa,~~ (Added, for the most part)
- [x] ~~Aerbunny,~~ (Added, for the most part)
- [x] Aerwhale, (In, but non-functioning)
- [x] Cockatrice, (In, but with incomplete animations)
- [x] Aechor plant, (In, but with incomplete models and textures)
- [ ] Zephyr,
- [ ] Zephyroo,
- [ ] Burrukai,
- [ ] Glitterwing (?),
- [ ] Glactrix (?),
- [ ] Kirrid,
- [ ] Carrion Sprout

**Comment by CDAGaming** [comment]
Closed for the time being due to an unknown issue with the contents breaking REST Api retrieval.

**Comment by Jack-Papel** [comment]
Closing as no longer relevant
