### ISSUE TITLE
Crash: Flax with -1 age

### ISSUE THREAD

**Issue by Mg138** [devs-immortal/Paradise-Lost#753]
### What were you doing when the crash occured? How can we replicate it?

We're not sure, but the player who reported it to us say they're now locked into crashing.

### Did it crash the client or server?

Client

### Mod Version

Beta 2.0.2

### Fabric API Version

qfapi-4.0.0-beta.26_qsl-3.0.0-beta.25_fapi-0.72.0

### Crash Report

```Shell
https://0x0.st/ohcp.log
```

### Other mods

https://codeberg.org/madeline/gaycraft

**Comment by Mg138** [comment]
Crash report: https://0x0.st/ohTV.txt

**Comment by NeezDu** [comment]
The same issue happened to our server, it's a Nitrado FTB Modpack; **_Medival Minecraft [Fabric] v.14.5 (1.19.2)_**. 
Procedure before issue was made as follows:
- Use Bone Meal repeatedly until the top block of the Flax plant is left
- Leave top block of the mature Flax plant with a planted Flax plant below then sleep
- After morning cycle, approach said Flax plant

After this, the crash occurred, and any attempt to enter the server results into a crash. What happened during the process is that the mature Flax plant left the top part unbroken, while using the bone meal repeatedly to speed up the growth process. The top part of the mature Flax plant was never broken and was left with a young Flax planted below.

A fix was made by removing the mod from the mod folder, loading the game to remove the soil that had the plant, then moved back the mod again before loading the game with the mod installed.

Crashed on a Server
JAR file used on modpack: paradise-lost-2.0.2-beta+1.19.2.jar

attached is the crash report screenshot from the mod

![image](https://user-images.githubusercontent.com/123179717/213720294-e7c058c3-953f-4afb-95a4-f4c0de976517.png)

**Comment by MBatt1** [comment]
Can you provide a video of some sort, I'm unable to follow the steps to reproduce, it's impossible to plant seeds below a grown flax crop, even with /setblock, as the top half will break. I'm not sure how this bug exists in 2.0.2, as it should have been fixed in 2.0.0
